name: flutter_servicos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Verifique a versão SDK do seu Flutter aqui

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.5           # Para fazer requisições HTTP ao backend
  url_launcher: ^6.1.7    # Para abrir links como o WhatsApp diretamente do app
  provider: ^6.0.5        # Opcional, para gerenciamento de estado

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
